server:
  port: ${PORT}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

  #core database
core:
  database:
    user: root
    password: Azazel123321
    url: jdbc:mysql://localhost:3306/uplan
    autocommit: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


spring:
  sleuth:
    baggage-keys:
      - context-user
