server:
  port: ${PORT}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${REPO_ACCOUNT_NAME}
          password: ${REPO_ACCOUNT_PASSWORD}
  application:
    name: uplan-config-server