server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 50
    time-unit: MILLISECONDS
    time-to-live: 10000
  ignoredHeaders: false
  ignoreSecurityHeaders: false
  routes:
    uplan:
      sensitiveHeaders:
      path: /hyh/**

ribbon:
  eureka:
    enable: true
  isSecure: false
  ReadTimeout: 8000
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 21000

jwt:
  token:
    secret: kbob123123

spring:
  sleuth:
    baggage-keys:
      - context-user